### PR TITLE
add nightlight script and dmenublocks action

### PR DESCRIPTION
**Pull request by bubstance**
Just a little option to toggle a "nightlight" mode. Requires `xsct`.

### CODE REVIEW

**Comment by pineapples5972** [comment]
It would be good to have some statusbar icon showing its on. Even tho its obvious its on but turning battery icon into crescent moon wont hurt. just suggesting.

**Comment by bubstance** [comment]
Would adding the moon at the end be a fair compromise? It feels a bit off to completely replace the other status indicators (not charging, charging, stagnant, etc).

**Comment by appeasementPolitik** [comment]
On my system I have redshift-minimal installed from the AUR autostarted from ~/.xprofile which is also an option

**Comment by public-void-ryan** [comment]
Moons show up twice if you have multiple batteries
pic-selected-220903-1225-56
.

**Comment by bubstance** [comment]
> Moons show up twice if you have multiple batteries.

Ah, probably should have seen that coming.

I don't have any machines with multiple batteries, so I don't really have a way to test locally. Does moving it to the end of the line do anything?

`printf "%s%s%d%%" "$status" "$warn" "$capacity" ; unset warn; echo "$night"` or something to that effect?

**Comment by public-void-ryan** [comment]
> done && printf "$night" "\\n"

yes this works perfect!

**Pull request closed without merging**
