### PR TITLE
Check if bgloc is valid, better notifications, updated postrun

### PR DESCRIPTION
**Pull request by vowkn**
Also fixed a typo in the comments, removed an extra slash on the "$bgloc" path and included the filename of the set wallpaper in the notification text.

### CODE REVIEW

**Comment by LukeSmithxyz** [comment]
dunst is certainly not autorestarted on my machine. I am using Artix, so it might just be a habit of systemd then. Either, way I don't think it's safe to assume it will autostart.

Don't remove the "extra" slash. Extra slashes cause no problem, but if the user has set the variable to something without a trailing slash, it could cause big problems.

Why exactly have you moved the command for killing dunst? It wouldn't be restarted if someone ran wal directly then.

**Comment by vowkn** [comment]
Fair points, on my base Arch installation it worked just fine, I didn't realize the autorestarting was a systemd thing.

My reasoning for killing dunst in the setbg script is so that it uses the color scheme of the new wallpaper for the notification. Currently it is restarted in the postrun script, which happens after wal has generated said color scheme.

The idea is that if someone is using this script for setting their wallpaper, they shouldn't need to use wal directly anymore. I have already made a pull request which should add xwallpaper support for pywal, though. Hopefully that will make things much simpler.

I'm also trying to remove the need for feh entirely on my system, and watching your sxiv video convinced me.

**Comment by vowkn** [comment]
Okay, so I've made a few tweaks to the script taking your comment into account. Good news is that the "extra" slash is back and I've removed the part where dunst is restarted (postrun should do it).

Bad news is that the notification showing is inconsistent for me. If postrun has finished running before the script gets to the notify-send command, it will show the notification, if not, it won't. I can add a sleep to make sure it ends, but that seems hacky at best.

Also, @dylanaraps has already accepted my pull request and xwallpaper is now supported by pywal (https://github.com/dylanaraps/pywal/commit/5c34f4e68907898c2a80b57727972e16e0621d2c). Pywal too saves the last used wallpaper and color scheme (wal -R) and supports selecting a random wallpaper if running it on a directory.

That sadly makes this script kind of obsolete if using pywal except for the notification part, which could be easily added to the postrun script itself (solving the notification issue I just mentioned), right?

In any case, this is the current status of the script:
```
#!/bin/sh

# This script does the following:
#   - Run by itself, set the wallpaper (at X start).
#   - If given a file, set that as the new wallpaper.
#   - If given a directory, choose random file in it.
#   - If wal is installed, also generate a colorscheme.

# Location of link to wallpaper.
bgloc="${XDG_CACHE_HOME:-$HOME/.cache/}/bg"

[ ! -L "$bgloc" ] && [ ! -e "$1" ] && printf 'Please provide a valid image or directory.\n' && exit 1

[ -f "$1" ] && ln -sf "$(readlink -f "$1")" "$bgloc"

[ -d "$1" ] && ln -sf "$(find "$(readlink -f "$1")" -iregex '.*.\(jpg\|jpeg\|png\)' -type f | shuf -n 1)" "$bgloc"

# If pywal is installed, use it.
if [ $(command -v wal) ]; then
  wal -qsti "$(readlink -f "$bgloc")" -o "${XDG_CONFIG_HOME:-$HOME/.config}/wal/postrun"
else
  xwallpaper --zoom "$bgloc" &
fi

notify-send -u low -i "$bgloc" 'Wallpaper updated' "$(basename "$(readlink -f "$bgloc")")"
```

I know you don't usually like full "if" statements, but in this case it makes the script much more readable.

Please let me know what you think about just using pywal directly to set the wallpaper (using the newly supported xwallpaper) or if I should update the pull request with the modifications I made (or any other further suggestions).

Sometimes less is more. Personally, I think the best solution would be to just add a function to .zshrc similar to the following one and edit the postrun script to include the notification:
```
setbg() { wal -qsti "$1" -o "${XDG_CONFIG_HOME:-$HOME/.config}/wal/postrun"; }
```

**Comment by vladdoster** [comment]
> @LukeSmithxyz Okay, so I've made a few tweaks to the script taking your comment into account. Good news is that the "extra" slash is back and I've removed the part where dunst is restarted (postrun should do it).
> 
> Bad news is that the notification showing is inconsistent for me. If postrun has finished running before the script gets to the notify-send command, it will show the notification, if not, it won't. I can add a sleep to make sure it ends, but that seems hacky at best.
> 
> Also, @dylanaraps has already accepted my pull request and xwallpaper is now supported by pywal ([dylanaraps/pywal@5c34f4e](https://github.com/dylanaraps/pywal/commit/5c34f4e68907898c2a80b57727972e16e0621d2c)). Pywal too saves the last used wallpaper and color scheme (wal -R) and supports selecting a random wallpaper if running it on a directory.
> 
> That sadly makes this script kind of obsolete if using pywal except for the notification part, which could be easily added to the postrun script itself (solving the notification issue I just mentioned), right?
> 
> In any case, this is the current status of the script:
> 
> ```shell
> #!/bin/sh
> 
> # This script does the following:
> #   - Run by itself, set the wallpaper (at X start).
> #   - If given a file, set that as the new wallpaper.
> #   - If given a directory, choose random file in it.
> #   - If wal is installed, also generate a colorscheme.
> 
> # Location of link to wallpaper.
> bgloc="${XDG_CACHE_HOME:-$HOME/.cache/}/bg"
> 
> [ ! -L "$bgloc" ] && [ ! -e "$1" ] && printf 'Please provide a valid image or directory.\n' && exit 1
> 
> [ -f "$1" ] && ln -sf "$(readlink -f "$1")" "$bgloc"
> 
> [ -d "$1" ] && ln -sf "$(find "$(readlink -f "$1")" -iregex '.*.\(jpg\|jpeg\|png\)' -type f | shuf -n 1)" "$bgloc"
> 
> # If pywal is installed, use it.
> if [ $(command -v wal) ]; then
>   wal -qst -i "$(readlink -f "$bgloc")" -o "${XDG_CONFIG_HOME:-$HOME/.config}/wal/postrun"
> else
>   xwallpaper --zoom "$bgloc" &
> fi
> 
> notify-send -u low -i "$bgloc" 'Wallpaper updated' "$(basename "$(readlink -f "$bgloc")")"
> ```
> 
> I know you don't usually like full "if" statements, but in this case it makes the script much more readable.
> 
> Please let me know what you think about just using pywal directly to set the wallpaper (using the newly supported xwallpaper) or if I should update the pull request with the modifications I made (or any other further suggestions).
> 
> Sometimes less is more. Personally, I think the best solution would be to just add a function to .zshrc similar to the following one and edit the postrun script to include the notification after restarting dunst:
> 
> ```shell
> setbg() { wal -qst -i "$1" -o "${XDG_CONFIG_HOME:-$HOME/.config}/wal/postrun"; }
> ```
> 
> ```shell
> bgloc=$(cat "${HOME}/.cache/wal/wal")
> notify-send -u low -i "$bgloc" 'Wallpaper updated' "$(basename "$bgloc")"
> ```
> 
> You would also have to use `wal -qRst` in your .xprofile instead of `setbg`. You can test it yourself by installing the latest Pywal version (pywal-git on the AUR).
> 
> That is my current setup and it works flawlessly!

Are you running Artix?

**Pull request closed without merging**
