### PR TITLE
fix(hibernate in sxhkd)

### PR DESCRIPTION
**Pull request by vladdoster**
I'm not too sure what `zzz` is, but in i3 it is achieved a separate way. Hibernate should work now.

### CODE REVIEW

**Comment by LukeSmithxyz** [comment]
zzz is for runit devices. What I'd really like is a hibernate bind universal for init systems. Probably some obvious command I've overlooked.

**Comment by drake-newell** [comment]
> zzz is for runit devices. What I'd really like is a hibernate bind universal for init systems. Probably some obvious command I've overlooked.

As far as I know, there is. It's called pm-utils (it's in the aur).

**Comment by LukeSmithxyz** [comment]
Things you have to install from the AUR by definition aren't universal.

**Comment by drake-newell** [comment]
> Things you have to install from the AUR by definition aren't universal.

Forgot to mention that it's also in the void main repos and debian main repos.  It's a fair bit more complicated that zzz, but it works with any init system.

**Pull request closed without merging**
