### PR TITLE
Improve `dropdowncalc` - use python with preloaded math lib

### PR DESCRIPTION
**Pull request by kiprasmel**
before: 

image

after:

image

### CODE REVIEW

**Comment by LukeSmithxyz** [comment]
Actually, this script isn't used anymore since i3 was removed, so I should remove it as well.

**Comment by kiprasmel** [comment]
oh no luke sorry to say but we still use i3 :/
you don't have to delete them c:

**Comment by katrushenkov** [comment]
> oh no luke sorry to say but we still use i3 :/
> you don't have to delete them c:

Anyway there is no i3 in voidrice anymore.

**Comment by void00r** [comment]
I think for the sake of convenience i3 shouldnt be removed. Cuz we still need straight foward easy to install and configurable WM which is not as complex as dwm and doesnt not breaks in times for crisis.

**Pull request closed without merging**
