### PR TITLE
Plugin to highlight hex color codes

### PR DESCRIPTION
**Pull request by charlie39**
Visually intuitive for editing hex color codes in Xresources /XDefaults  and anywhere else

### CODE REVIEW

**Comment by charlie39** [comment]
clumsy hands

**Comment by narukeh** [comment]
just tested, this plugin is great!!!

**Comment by charlie39** [comment]
https://github.com/LukeSmithxyz/voidrice/pull/591#issuecomment-618373567
ikr, very handy for testing different colours

**Comment by vladdoster** [comment]
This is useful!

**Comment by charlie39** [comment]
@vladdoster thanks

**Pull request merged**
