### PR TITLE
Sets the correct DPI for your monitor instead of the the generic '96'

### PR DESCRIPTION
**Pull request by salman-abedin**

### CODE REVIEW

**Comment by d351d3r** [comment]
Thank you!

**Comment by salman-abedin** [comment]
My pleasure. Doesn't your fonts look just perfect! Or is it just my autism? lol.

**Comment by d351d3r** [comment]
> My pleasure. Don't your fonts look just perfect now! Or is it just my autism? lol.

It didn't help me, but it looks very impressive :)

**Comment by salman-abedin** [comment]
Looks impressive! Wow! That's the greatest complement any coder can ever get. lol.

**Comment by Architector4** [comment]
I think it's down to preference. I personally like fixed 72 DPI value, so that 12pt = 12px and so that "12pt" would always represent a fixed value of pixels, and so that stuff wouldn't get comically large or disproportionally scaled.

**Comment by salman-abedin** [comment]
I reckon that DPI levels are subjective. That is exactly why I took that into account when writing the script and strayed away from modifying present settings.
But, if you are one those people who is reluctant to tinker with the levels and just want the best possible value, my script will set that for you.

**Comment by kronikpillow** [comment]
this script has completly broken my desktop, it rendered it completly useless, I don't see the dwm bar, I can't even launch a st terminal ... I had to git reset --hard origin/master to undo this because for some reason even after removing the script from xprofile it didn't undo the changes

**Comment by kiprasmel** [comment]
@kronikpillow too bad. Don't run things you do not understand!

**Comment by kiprasmel** [comment]
@Sadoon-AlBader fyi, see the following resources:

https://wiki.archlinux.org/index.php/Xorg#Display_size_and_DPI, especially:
https://wiki.archlinux.org/index.php/Xorg#Setting_DPI_manually (which recommends to set the DPI to exact specified values "to reduce scaling artifacts to GUI that use bitmaps"

**Comment by Sadoon-AlBader** [comment]
> @Sadoon-AlBader fyi, see the following resources:

I believe you wanted to mention @salman-abedin not me :)

**Comment by kiprasmel** [comment]
> I believe you wanted to mention @salman-abedin not me :)

github's auto-complete somehow completed you not Salman 😅 sorry for the spam guys!

**Pull request closed without merging**
