### PR TITLE
Refreshing dwm status bar using signals.

### PR DESCRIPTION
**Pull request by msinkec**
True chads use signals and traps.
No, seriously, it's much more efficient.

### CODE REVIEW

**Comment by LukeSmithxyz** [comment]
Well the true chad solution would have different signals for each module like i3blocks, but that's next on the list.

**Comment by jmauss** [comment]
Hey guys, trying to work on a similar setup. I have "pkill -SIGTRAP dwmbar" in my refbar script, but it doesn't seem to do anything. Once I change it to "pkill -SIGTRAP bash", it seems to update the bar immediately, but I don't want to cause other problems by doing this. How do I get the process to register as dwmbar rather than bash?

dwmbar is located in .local/bin which I have confirmed is in my $PATH. refbar is in the same location, and dwmbar is called in my .xprofile with "dwmbar &"

Thanks!

**Comment by msinkec** [comment]
Can you post your scripts?

**Comment by jmauss** [comment]
They can be found here: https://github.com/jmauss/Scripts

We can either continue discussion on this thread or somewhere on my repo if that makes more sense. Thanks for the help!

**Pull request merged**
