### PR TITLE
Unmessy login screen

### PR DESCRIPTION
**Pull request by salman-abedin**

### CODE REVIEW

**Comment by hamidout** [comment]
love this, much looks cleaner

**Comment by salman-abedin** [comment]
Yeah, It looked like a redundancy to me but since I got this from the arch wiki, I figured I should do my homework (which I haven't yet, =) ) before dismissing it.

**Comment by salman-abedin** [comment]
> And why exactly do you need the `-- vt1` thing when it already works?

Yeah, It looks like a redundancy to me but since I got this from the arch wiki, I figured I should do my homework (which I haven't yet done, XD ) before dismissing it.

**Comment by narukeh** [comment]
@salman-abedin  i say `exec startx > $XDG_DATA_HOME/startx.log 2>&1`
It's still unmessy, plus you don't loose any info 😉

**Pull request closed without merging**
