### PR TITLE
binding for copying to clipboard

### PR DESCRIPTION
**Pull request by frogtile**

### CODE REVIEW

**Comment by LukeSmithxyz** [comment]
neovim already uses the system clipboard.

**Comment by frogtile** [comment]
> neovim already uses the system clipboard.

This reduces keystrokes

**Comment by LukeSmithxyz** [comment]
How is <leader>y shorter than just y?

**Comment by frogtile** [comment]
> How is <leader>y shorter than just y?

just `y` doesn't copy to clipboard.

**Comment by frogtile** [comment]
@LukeSmithxyz can you please explain what is going on?

**Comment by frogtile** [comment]
@LukeSmithxyz please?

**Pull request closed without merging**
