### PR TITLE
dwm compliant

### PR DESCRIPTION
**Pull request by charlie39**
revised PR
simply displaying the current song playing [or paused] in  status bar in dwm.

### CODE REVIEW

**Comment by LukeSmithxyz** [comment]
Use pidof instead of pgrep. Much, much faster. I've been trying to switch all my pgreps over.

**Comment by charlie39** [comment]
Okay dokay, I will do that .

I am going through the repo and saw some overhaul since the time I used. 
I have some questions now, 

1. where is i3blocks/dwmblocks is initialized since it's separate for both now?

2. Where is mpd-module-update script used since I don't see it in xinitrc ? this PR is dependent on that no?

3. $ALSA_CONFIG_PATH isn't really helpful.
if one uses that and moves the ~/.asoundrc there, then aplay -l throws errors. I think I will open an issue on this.

**Comment by charlie39** [comment]
I mean in the xprofile not in xinitrc.
I see this, 
https://github.com/LukeSmithxyz/voidrice/issues/577#issue-602282674

**Comment by LukeSmithxyz** [comment]
Yeah I've noticed the ALSA thing doesn't work as expected. The dotfiles don't use ALSA anymore anyway though. Or at least they use Pulseaudio.

The music statusbar module is not active by default now due to some problems I hadn't bothered to solve. I think a recent PR might've fixed them though.

i3blocks is started by i3. dwmblocks is started by dwm.

**Pull request closed without merging**
