### PR TITLE
Use `pkill` instead of `killall`

### PR DESCRIPTION
**Pull request by anntnzrb**
The `killall` command doesn't come shipped in all distributions (Void
Linux as an example), on the other hand `pkill` does.

Unsure what the exact intention on each call is but the `-9` signal can be
replaced with `-x` if the intention is not to end all instances.

Also note that I left `pkill -x Xorg` without the `-9` signal because
for some reason it won't function as expected and end up halting the
system (at least on Void Linux).

### CODE REVIEW

**Comment by narukeh** [comment]
how about 
```
kill -9 $(pidof "$1")
```
😄 funny if pidof isnt shipped either 😄

**Comment by anntnzrb** [comment]
> how about
> 
> ```
> kill -9 $(pidof "$1")
> ```
> 
>  funny if pidof isnt shipped either

Interestingly enough, I'm doing some tests with `pidof` as for some reason `screenkey` does not get recognized by it, but does effectively get recognized with `pgrep` instead...

**Comment by anntnzrb** [comment]
Updated; the correct way of terminating is using `SIGTERM`;
`SIGKILL` should be avoided.

Source: [In what order should I send signals to gracefully shutdown processes?](https://stackoverflow.com/a/37692419)

**Comment by LukeSmithxyz** [comment]
Well, even using SIGTERM, I'm not sure. It *definitely* needs `-x`, though. `pkill` will kill any process with the given match in its name without `-x`.

**Pull request closed without merging**
