### PR TITLE
Make kbselect independent from xkblayout-state

### PR DESCRIPTION
**Pull request by MYDavoodeh**
There is no need for another whole, extra package.
A simple grep filter can give the same results.

### CODE REVIEW

**Comment by tomicp** [comment]
Nicely done.

**Comment by hamidout** [comment]
you forgot to end quote `notify-send "⌨  Keyboard/language module" "$(printf "%s" "\- Current layout: $(setxkbmap -query | grep -oP 'layout:\s*\K\w+')")"`

**Comment by MYDavoodeh** [comment]
No I didn't. The end quote is in the next line.

**Comment by hamidout** [comment]
oh, my bad

**Pull request merged**
