### PR TITLE
Add backlight control as a scroll function

### PR DESCRIPTION
**Pull request by Sadoon-AlBader**
This adds backlight control of monitor through scrolling.
Requires "light" pacakage and that the user can run "sudo light" without a password, easily done through sudoers edit.
Enjoy less eye strain :)

### CODE REVIEW

**Comment by drake-newell** [comment]
Maybe change it to use xbacklight instead? That's the LARBS default.

**Comment by Sadoon-AlBader** [comment]
> Maybe change it to use xbacklight instead? That's the LARBS default.

So I tried xbacklight and light on two different laptops (Acer Aspire S7 392, HP Envy x360 13 Ryzen 2500U)
xbacklight works on the Acer, but not the HP, while light works on both.
xbacklight seems to have trouble detecting the screen on the HP.

**Comment by Trebled** [comment]
Xbacklight doesn't work w/ my Acer either, thanks. 
(P.S. I found sudo to be unnecessary so long as you've appended yourself to Group video.😺)

**Comment by Sadoon-AlBader** [comment]
> Xbacklight doesn't work w/ my Acer either, thanks.
> (P.S. I found sudo to be unnecessary so long as you've appended yourself to Group video.)

You're most welcome :)
Actually I just noticed today that sudo isn't necessary, but good catch on why it isn't!

**Pull request merged**
