### PR TITLE
Cool xcompmgr transition without using any extra resources &  Salman Abedin Efficient scripting to figure out the directory path 

### PR DESCRIPTION
**Pull request by salman-abedin**

### CODE REVIEW

**Comment by vladdoster** [comment]
Where is notion that you get the flag enabled features for free coming from?

**Comment by salman-abedin** [comment]
> Where is notion that you get the flag enabled features for free coming from?

Benchmarking of course!

**Comment by vladdoster** [comment]
Mind posting your benchmarks? Using something like valgrind or what? I'm not trying to interrogate you haha, I'm genuinely interested about performance benchmarking.

**Comment by salman-abedin** [comment]
Unfortunately, I've got nothing to show for as my benchmarking was pretty hacky. lol.  I have a statusbar module that updates each second and for each cases of xcompmgr, I just monitored the cpu load and ram useage while moving the hell out of my workspaces. lol.

**Comment by vladdoster** [comment]
Or at least tell me what to do. I'm always trying to add performance validation to my aresenal of knowledge. Recently started using cprofile for python apps. Good stuff

**Pull request closed without merging**
