### PR TITLE
Use nvim for coloured man pages.

### PR DESCRIPTION
**Pull request by iamantu93**
You can even quit using q instead of  :q.

### CODE REVIEW

**Comment by Daja177** [comment]
It's an interesting idea, but I'm not really sure I necessarily see the benefit of this.

Since man-pages are meant to be read and not necessarily written to, I find that reading them using `vim` is more of a hassle than using `less` due to the difference in how you scroll in those programs. I've also noticed that the loading time when opening man-pages is longer when using your suggested environment variable. Besides, the environment variables in Luke's `.profile` file already gives `man` colors, although admittedly it's not as detailed as `vim`'s syntax highlighting.

It'd be great if you could provide some more information in regards to the benefits of using this instead, in case there's something I've missed.

**Comment by iamantu93** [comment]
Luke and everyone like the vim keys so much. If you use neovim as a manpager you can use vim keys to navigate. Instead of several environment variables you can achieve colour manpages using only one variable. I haven't noticed any longer loading time.

**Comment by Daja177** [comment]
@iamantu93 `less` uses vi-keys though (at least some of the navigation ones). You scroll up and down with `k` and `j`, half a page up and down with `u` and `d`.

**Comment by LukeSmithxyz** [comment]
This doesn't really yield any advantage. And it certainly is laggy on my system. Additionally, less is a program used for many different purposes so if I did abandon it for reading manuals, I wouldn't want to remove those variables for coloring it in other uses.

**Pull request closed without merging**
