### PR TITLE
Added note to change parameter for urxvt users

### PR DESCRIPTION
**Pull request by LoganDungeon**
It took me a while to realize the error, so this might spare some time of other urxvt users.

### CODE REVIEW

**Comment by LoganDungeon** [comment]
Maybe you even want to add another if else branch checking which terminal emulator is used.

**Comment by dawidpotocki** [comment]
Well, it can be different with any terminal emulator, so you would have to write down pretty long list. For example, Alacritty uses `--class` flag. Same with GUI applications, it can be different.

**Comment by LoganDungeon** [comment]
I guess you are right.
We can see what Luke thinks about this and he can just delete this PR if he wants.

**Comment by LukeSmithxyz** [comment]
To avoid bloat creep, I make it an issue to not accommodate documentation/case handling of software not in LARBS. This sounds autistic, but otherwise it would be nothing by documentation and hand-holding ad-hockery.

If users are smart enough to change their terminals, they are smart enough to notice this problem and find the solution.

**Pull request closed without merging**
